-- Migration number: 0005 	 2025-03-01T19:53:07.235Z

ALTER TABLE email_routes
ADD COLUMN `drop` INTEGER NOT NULL DEFAULT 0 CHECK (`drop` IN (0, 1));

ALTER TABLE email_routes
ADD COLUMN received INTEGER NOT NULL DEFAULT 0;

ALTER TABLE email_routes
ADD COLUMN sent INTEGER NOT NULL DEFAULT 0;