// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DISCORD_HOOK_URL: "https://discord.com/api/webhooks/1147295373497475212/AHT7hmNNZDEj2sUi6SSTz4n1YHzGHU5rbXVnpO9b-IkxHp6aXrji0fwyAbtAz9WqWa_I";
	EMAIL_FORWARD_TO: "shihabmridha@gmail.com";
}
