#:schema node_modules/wrangler/config-schema.json
name = "cf-email-handler"
main = "src/index.ts"
compatibility_date = "2024-12-05"
assets = { directory = "dist/" }

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "cf-email-handler"
database_id = "6e1fed9c-07c4-487b-a946-9e64695138d3"

[vars]
DISCORD_HOOK_URL = "https://discord.com/api/webhooks/1147295373497475212/AHT7hmNNZDEj2sUi6SSTz4n1YHzGHU5rbXVnpO9b-IkxHp6aXrji0fwyAbtAz9WqWa_I"
EMAIL_FORWARD_TO = "shihabmridha@gmail.com"
AI_ENDPOINT="https://gateway.ai.cloudflare.com/v1/aa4860f2766d7f93f6685ce382da26f5/cf-email-handler/google-ai-studio"
JWT_SECRET="secret"
